# Generated by Django 5.2.4 on 2025-08-05 07:25

import attendance_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='image',
        ),
        migrations.AddField(
            model_name='member',
            name='face_file',
            field=models.FileField(blank=True, null=True, upload_to=attendance_app.models.protected_face_upload_path),
        ),
    ]
