# Generated by Django 5.2.4 on 2025-08-05 07:33

import attendance_app.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_remove_member_image_member_face_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='face_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='F:\\Django\\Main Projects\\FaceTrack_Attendance_System\\face_attendance\\secure_faces'), upload_to=attendance_app.models.protected_face_upload_path),
        ),
    ]
