# Generated by Django 5.2.4 on 2025-08-05 08:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0005_alter_member_face_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='face_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='F:\\Django\\Main Projects\\FaceTrack_Attendance_System\\face_attendance\\secure_faces'), upload_to='secure_faces'),
        ),
    ]
